minVersion: '0.32.0'
changelogPolicy: auto
preReleaseCommand: node ../../scripts/pre-release.js

releaseBranchPrefix: release/react-embed

requireNames:
  - /^formsort-react-embed-v.+\.tgz$/
targets:
  - name: npm
  - name: github
    tagPrefix: react-embed-
