minVersion: '0.32.0'
changelogPolicy: auto
preReleaseCommand: node ../../scripts/pre-release.js

releaseBranchPrefix: release/eslint-config

requireNames:
  - /^formsort-eslint-config-v.+\.tgz$/
targets:
  - name: npm
  - name: github
    tagPrefix: eslint-config-
