minVersion: '0.32.0'
changelogPolicy: auto
preReleaseCommand: node ../../scripts/pre-release.js

releaseBranchPrefix: release/web-embed-api

requireNames:
  - /^formsort-web-embed-api-v.+\.tgz$/
targets:
  - name: npm
  - name: github
    tagPrefix: web-embed-api-
