minVersion: '0.32.0'
changelogPolicy: auto
preReleaseCommand: node ../../scripts/pre-release.js
postReleaseCommand: node ../../scripts/post-release.js

releaseBranchPrefix: release/tsconfig

requireNames:
  - /^formsort-tsconfig-v.+\.tgz$/
targets:
  - name: npm
    access: public
  - name: github
    tagPrefix: tsconfig-
