name: Build

on:
  push:
    branches:
      - master
      - release/*/*
  pull_request:
    branches: [master]
  workflow_call:
    inputs:
      ref:
        description: The branch to build
        type: string
        required: true
      package:
        description: The package to build
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.ref }}
      # We need this as we use this workflow from
      # release.yml, which has a different SHA from
      # the `github` context we have here.
      # Otherwise we could just use `github.sha`
      - name: Get SHA
        id: sha
        run: >-
          echo ::set-output name=sha::$(git rev-parse HEAD)
      - uses: ./.github/actions/setup-node
      # We build all ahead of time before linting as we need the build
      # step for TS type definitions to be usable. These are used during both
      # linting and testing.
      # Even more, we need to build the two specific ones first as their type
      # definitions are required for the other project builds.
      # TODO(byk): Streamline this a bit and run the rest of the build in parallel
      - name: Build prerequisites first
        run: |
          yarn workspace @formsort/constants run build
          yarn workspace @formsort/web-embed-api run build
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Pack all
        if: ${{ !inputs.package }}
        run: yarn workspaces run pack
      - name: Pack single package
        if: ${{ inputs.package }}
        run: yarn workspace @formsort/${{ inputs.package }} run pack
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.sha.outputs.sha }}
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/packages/**/*.tgz
            !node_modules/**/*
