name: Publish

on:
  workflow_run:
    workflows: [Cut a Release]
    types:
      - completed

jobs:
  inputs:
    name: Get release info
    runs-on: ubuntu-latest
    outputs:
      package: ${{ steps.inputs.outputs.package }}
      version: ${{ steps.inputs.outputs.version }}
    steps:
      - name: Download parent inputs file
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ github.token }}
          workflow: 'Cut a Release'
          run_id: ${{ github.event.workflow_run.id }}
          name: ${{ github.event.workflow_run.id }}-inputs

      - name: Set parent inputs
        id: inputs
        run: |
          echo ::set-output name=package::$(jq -r '.package' inputs.json)
          echo ::set-output name=version::$(jq -r '.version' inputs.json)
          rm inputs.json

  publish:
    runs-on: ubuntu-latest
    needs: inputs
    environment: release
    name: 'Publish the new version'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CRAFT_LOG_LEVEL: Trace
        # Run `craft publish` with `--no-status-check` here as we already depend on the previous step
        # "Build" to finish. Also, if that fails we won't be able to find the artifacts at this stage.
        run: >-
          yarn workspace @formsort/${{ needs.inputs.package }} run craft publish ${{ needs.inputs.version }} --no-status-check
