name: Publish Package
on:
  workflow_dispatch:
    inputs:
      package:
        description: Name of the package to release
        required: true
      version:
        description: Version to release
        required: true
env:
  GIT_COMMITTER_NAME: Formsort Release Bot
  GIT_AUTHOR_NAME: Formsort Release Bot
  EMAIL: releases@formsort.com
jobs:
  prepare:
    runs-on: ubuntu-latest
    name: 'Prepare a new version'
    outputs:
      release_branch: ${{ steps.prepare.outputs.release_branch }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node
      - name: Prepare
        id: prepare
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          release_branch=$(yarn workspace @formsort/${{ github.event.inputs.package }} run craft prepare ${{ github.event.inputs.version }} | grep -Po '(?<=Pushing the release branch ")release/.+/.+(?=")')
          echo ::set-output name=release_branch::$release_branch

  build:
    name: Build
    needs: prepare
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ needs.prepare.outputs.release_branch }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment: release
    name: 'Publish the new version'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        # Run `craft publish` with `--no-status-check` here as we already depend on the previous step
        # "Build" to finish. Also, if that fails we won't be able to find the artifacts at this stage.
        run: >-
          yarn workspace @formsort/${{ github.event.inputs.package }} run craft publish ${{ github.event.inputs.version }} --no-status-check
